/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NotebookUI;

import NotebookController.DBConnection;
import NotebookController.Notes;
import NotebookController.User;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/**
 *
 * @author Silviu
 */
public class CreateNote extends javax.swing.JFrame {


    int xMouse;
    int yMouse;
    Notes n;
    public User u;
    
    /**
     * Creates new form CreateNote
     */
    public CreateNote(User u) {
        initComponents();
        this.u = u;
        Date();
        userProfile(u);
    }
    public void Date(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        Date.setText(year +"-" + (month+1) +"-" + day );
    }  
    public void userProfile(User u) {
    if(u != null){
        
        UserName3.setText(u.getUsername());
        
        }
    }

    private CreateNote() {}
    public void Notes() {}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseB = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        addimage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextPane();
        NoteImage = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        nr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        UserName1 = new javax.swing.JLabel();
        UserName2 = new javax.swing.JLabel();
        UserName3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        Date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(770, 10, 20, 20);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(730, 10, 30, 20);

        Save.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save);
        Save.setBounds(310, 530, 90, 50);

        addimage.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        addimage.setText("Update");
        addimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addimageActionPerformed(evt);
            }
        });
        getContentPane().add(addimage);
        addimage.setBounds(430, 530, 100, 50);

        Description.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(Description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 130, 450, 380);

        NoteImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Male.png"))); // NOI18N
        getContentPane().add(NoteImage);
        NoteImage.setBounds(20, 200, 250, 280);

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag);
        FrameDrag.setBounds(0, 0, 710, 30);

        Title.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 255));
        Title.setText("Title");
        getContentPane().add(Title);
        Title.setBounds(20, 130, 250, 30);

        nr.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        nr.setForeground(new java.awt.Color(0, 0, 255));
        nr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrActionPerformed(evt);
            }
        });
        getContentPane().add(nr);
        nr.setBounds(70, 90, 40, 30);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Description");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 90, 150, 20);

        jButton9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton9.setText("Notes");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(560, 530, 90, 50);

        UserName1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        UserName1.setForeground(new java.awt.Color(0, 0, 255));
        UserName1.setText("Nr :");
        getContentPane().add(UserName1);
        UserName1.setBounds(30, 90, 30, 30);

        UserName2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        UserName2.setForeground(new java.awt.Color(0, 153, 0));
        UserName2.setText("Hy");
        getContentPane().add(UserName2);
        UserName2.setBounds(310, 30, 40, 40);

        UserName3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        UserName3.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(UserName3);
        UserName3.setBounds(360, 30, 110, 40);

        jButton8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(670, 530, 90, 50);

        Date.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Date.setForeground(new java.awt.Color(0, 255, 51));
        getContentPane().add(Date);
        Date.setBounds(0, 10, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Bg.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        // TODO add your handling code here:
        this.setState(MyNotebook.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        JOptionPane.showMessageDialog(null ,"Chose a picture for your note!");
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(false);
        fc.showOpenDialog(this);
        File f=fc.getSelectedFile();
        ImageIcon path = new ImageIcon(f.getAbsolutePath());
        Rectangle rect =NoteImage.getBounds();
        Image scaledImage = path.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
        path = new ImageIcon(scaledImage);
        NoteImage.setIcon(path);
        try {
            FileInputStream fin = new FileInputStream(f);
            int len=(int) f.length();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3309/notebookdb?" +
                                     "user=root&password=");
            PreparedStatement ps = con.prepareStatement("Insert into notes(userId, title,text, noteimage) values(?,?,?,?)");
            ps.setInt(1,u.getId());
            ps.setString(2,Title.getText());
            ps.setString(3, Description.getText());
            ps.setBinaryStream(4, fin, len);
            int status = ps.executeUpdate();
            if(status>0) {
                JOptionPane.showMessageDialog(null, "Succesufully saved!");
                ps.close();
              } else{
                 JOptionPane.showMessageDialog(null, "Not inserted!");
                 ps.close();
            }
        } catch (FileNotFoundException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }


    }//GEN-LAST:event_SaveActionPerformed

        
    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void addimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addimageActionPerformed
   
        JOptionPane.showMessageDialog(null ,"Chose a picture for your note!");
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(false);
        fc.showOpenDialog(this);
        File f=fc.getSelectedFile();
        ImageIcon path = new ImageIcon(f.getAbsolutePath());
        Rectangle rect =NoteImage.getBounds();
        Image scaledImage = path.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
        path = new ImageIcon(scaledImage);
        NoteImage.setIcon(path);
        try {
            
            DBConnection conn = new DBConnection();
            Connection c = conn.getConnection();
            FileInputStream fin = new FileInputStream(f);
            int len=(int) f.length();
            PreparedStatement ps = c.prepareStatement("UPDATE `notes` SET `userId`=?,`title`=?,`text`=?,`noteimage`=? WHERE `id`=" + nr.getText());
            ps.setInt(1,u.getId());
            ps.setString(2,Title.getText());
            ps.setString(3, Description.getText());
            ps.setBinaryStream(4, fin, len);
            int status = ps.executeUpdate();
            
            if(status>0) {
                JOptionPane.showMessageDialog(null, "Succesufully saved!");
                ps.close();
              } else{
                 JOptionPane.showMessageDialog(null, "Not inserted!");
                 ps.close();
            }
        } catch (FileNotFoundException | SQLException e) {
            
        }
    }//GEN-LAST:event_addimageActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        this.dispose();
        MyNotes cm = new MyNotes(u);
        cm.setVisible(true);

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
        LogIn li=new LogIn();
        li.setVisible(true);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void nrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseB;
    public javax.swing.JLabel Date;
    public javax.swing.JTextPane Description;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JLabel MinB;
    public javax.swing.JLabel NoteImage;
    private javax.swing.JButton Save;
    public javax.swing.JTextField Title;
    private javax.swing.JLabel UserName1;
    private javax.swing.JLabel UserName2;
    private javax.swing.JLabel UserName3;
    private javax.swing.JButton addimage;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nr;
    // End of variables declaration//GEN-END:variables

    public void setIcon(ImageIcon newImage) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
